// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Request = 2,
  RequestLine = 3,
  Method = 4,
  Path = 5,
  Variable = 6,
  Header = 7,
  Key = 8,
  Function = 9,
  FunctionName = 10,
  Value = 11,
  BodyStart = 12,
  Body = 13,
  JsonBody = 14,
  FormBody = 15,
  TextBody = 16
