import { EditorColorsInput, PostchiTheme, SyntaxTokens, ThemeType, VarColors } from "./theme";
import { buildEditorTheme, buildSyntaxHighlighting, resolveEditorColors, resolveThemeVars } from "./theme-builder";

function defineTheme(config: {
    id: string;
    name: string;
    type: ThemeType;
    vars: VarColors;
    tokens: SyntaxTokens;
    editor?: EditorColorsInput;
}): PostchiTheme {
    const resolved = resolveThemeVars(config.vars);
    const editorColors = resolveEditorColors(config.editor, config.vars);
    return {
        id: config.id,
        name: config.name,
        type: config.type,
        vars: resolved,
        codemirror: {
            editorTheme: buildEditorTheme(editorColors, config.type === 'dark'),
            syntaxHighlighting: buildSyntaxHighlighting(config.tokens),
            tokens: config.tokens,
            colors: editorColors,
        },
        _source: {
            vars: config.vars,
            tokens: config.tokens,
            editor: config.editor,
        },
    };
}

// ── Dark Themes ──────────────────────────────────────────────

const postchiDark = defineTheme({
    id: 'postchi-dark',
    name: 'Postchi Dark',
    type: 'dark',
    vars: {
        '--primary': '#F00',
        '--primary-foreground': '#FFFFFF',
        '--background': '#111111',
        '--background-elevated': '#1A1A2E',
        '--background-panel': '#0D0D0D',
        '--foreground': '#ECECEC',
        '--muted': '#1E1E1E',
        '--muted-foreground': '#b6af9d',
        '--destructive': '#F38BA8',
        '--success': '#A6FFA1',
        '--error': '#DF0000',
        '--warning': '#F9E2AF',
    },
    tokens: {
        keyword: '#FF6188',
        string: '#8DFF8E',
        propertyName: '#60A4F1',
        variableName: '#E0DEF4',
        comment: '#6272A4',
        annotation: '#FFD580',
    },
});

const dracula = defineTheme({
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    vars: {
        '--primary': '#BD93F9',
        '--primary-foreground': '#282A36',
        '--background': '#21222C',
        '--background-elevated': '#282A36',
        '--background-panel': '#191A21',
        '--foreground': '#F8F8F2',
        '--muted': '#44475A',
        '--muted-foreground': '#6272A4',
        '--destructive': '#FF5555',
        '--success': '#50FA7B',
        '--error': '#FF5555',
        '--warning': '#F1FA8C',
    },
    tokens: {
        keyword: '#FF79C6',
        string: '#F1FA8C',
        propertyName: '#8BE9FD',
        variableName: '#F8F8F2',
        comment: '#6272A4',
        annotation: '#FFB86C',
    },
});

const cobalt = defineTheme({
    id: 'cobalt',
    name: 'Cobalt',
    type: 'dark',
    vars: {
        '--primary': '#FFC600',
        '--primary-foreground': '#193549',
        '--background': '#15232D',
        '--background-elevated': '#1B3A4B',
        '--background-panel': '#0D1F2D',
        '--foreground': '#E1EFFF',
        '--muted': '#1B3A4B',
        '--muted-foreground': '#7C9CB5',
        '--destructive': '#FF628C',
        '--success': '#3AD900',
        '--error': '#FF628C',
        '--warning': '#FFC600',
    },
    tokens: {
        keyword: '#FF9D00',
        string: '#A5FF90',
        propertyName: '#9EFFFF',
        variableName: '#E1EFFF',
        comment: '#0088FF',
        annotation: '#FFC600',
    },
});

const catppuccinMocha = defineTheme({
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    type: 'dark',
    vars: {
        '--primary': '#CBA6F7',
        '--primary-foreground': '#1E1E2E',
        '--background': '#1E1E2E',
        '--background-elevated': '#262637',
        '--background-panel': '#181825',
        '--foreground': '#CDD6F4',
        '--muted': '#313244',
        '--muted-foreground': '#6C7086',
        '--destructive': '#F38BA8',
        '--success': '#A6E3A1',
        '--error': '#F38BA8',
        '--warning': '#F9E2AF',
    },
    tokens: {
        keyword: '#CBA6F7',
        string: '#A6E3A1',
        propertyName: '#89B4FA',
        variableName: '#CDD6F4',
        comment: '#6C7086',
        annotation: '#FAB387',
    },
});

const tokyoNight = defineTheme({
    id: 'tokyo-night',
    name: 'Tokyo Night',
    type: 'dark',
    vars: {
        '--primary': '#BB9AF7',
        '--primary-foreground': '#1A1B26',
        '--background': '#1A1B26',
        '--background-elevated': '#24283B',
        '--background-panel': '#16161E',
        '--foreground': '#A9B1D6',
        '--muted': '#24283B',
        '--muted-foreground': '#565F89',
        '--destructive': '#F7768E',
        '--success': '#9ECE6A',
        '--error': '#F7768E',
        '--warning': '#E0AF68',
    },
    tokens: {
        keyword: '#BB9AF7',
        string: '#9ECE6A',
        propertyName: '#7AA2F7',
        variableName: '#C0CAF5',
        comment: '#565F89',
        annotation: '#FF9E64',
    },
});

const nord = defineTheme({
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    vars: {
        '--primary': '#88C0D0',
        '--primary-foreground': '#2E3440',
        '--background': '#2E3440',
        '--background-elevated': '#3B4252',
        '--background-panel': '#272C36',
        '--foreground': '#ECEFF4',
        '--muted': '#3B4252',
        '--muted-foreground': '#616E88',
        '--destructive': '#BF616A',
        '--success': '#A3BE8C',
        '--error': '#BF616A',
        '--warning': '#EBCB8B',
    },
    tokens: {
        keyword: '#81A1C1',
        string: '#A3BE8C',
        propertyName: '#88C0D0',
        variableName: '#D8DEE9',
        comment: '#616E88',
        annotation: '#D08770',
    },
});

const githubDark = defineTheme({
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    vars: {
        '--primary': '#A371F7',
        '--primary-foreground': '#FFFFFF',
        '--background': '#0D1117',
        '--background-elevated': '#161B22',
        '--background-panel': '#010409',
        '--foreground': '#C9D1D9',
        '--muted': '#21262D',
        '--muted-foreground': '#8B949E',
        '--destructive': '#F85149',
        '--success': '#3FB950',
        '--error': '#F85149',
        '--warning': '#D29922',
    },
    tokens: {
        keyword: '#FF7B72',
        string: '#A5D6FF',
        propertyName: '#79C0FF',
        variableName: '#C9D1D9',
        comment: '#8B949E',
        annotation: '#FFA657',
    },
});

const monokaiPro = defineTheme({
    id: 'monokai-pro',
    name: 'Monokai Pro',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#2D2A2E',
        '--background': '#2D2A2E',
        '--background-elevated': '#363339',
        '--background-panel': '#221F22',
        '--foreground': '#FCFCFA',
        '--muted': '#403E41',
        '--muted-foreground': '#727072',
        '--destructive': '#FF6188',
        '--success': '#A9DC76',
        '--error': '#FF6188',
        '--warning': '#FFD866',
    },
    tokens: {
        keyword: '#FF6188',
        string: '#FFD866',
        propertyName: '#78DCE8',
        variableName: '#FCFCFA',
        comment: '#727072',
        annotation: '#FC9867',
    },
});

const gruvbox = defineTheme({
    id: 'gruvbox',
    name: 'Gruvbox',
    type: 'dark',
    vars: {
        '--primary': '#D79921',
        '--primary-foreground': '#282828',
        '--background': '#292929',
        '--background-elevated': '#32302F',
        '--background-panel': '#242424',
        '--foreground': '#EBDBB2',
        '--muted': '#32302F',
        '--muted-foreground': '#928374',
        '--destructive': '#FB4934',
        '--success': '#B8BB26',
        '--error': '#FB4934',
        '--warning': '#FE8019',
    },
    tokens: {
        keyword: '#FB4934',
        string: '#B8BB26',
        propertyName: '#83A598',
        variableName: '#EBDBB2',
        comment: '#928374',
        annotation: '#FE8019',
    },
});

const oneDarkPro = defineTheme({
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    type: 'dark',
    vars: {
        '--primary': '#C678DD',
        '--primary-foreground': '#282C34',
        '--background': '#282C34',
        '--background-elevated': '#2C313A',
        '--background-panel': '#21252B',
        '--foreground': '#ABB2BF',
        '--muted': '#2C313A',
        '--muted-foreground': '#5C6370',
        '--destructive': '#E06C75',
        '--success': '#98C379',
        '--error': '#E06C75',
        '--warning': '#D19A66',
    },
    tokens: {
        keyword: '#C678DD',
        string: '#98C379',
        propertyName: '#61AFEF',
        variableName: '#ABB2BF',
        comment: '#5C6370',
        annotation: '#D19A66',
    },
});

const ayuDark = defineTheme({
    id: 'ayu-dark',
    name: 'Ayu Dark',
    type: 'dark',
    vars: {
        '--primary': '#E6B450',
        '--primary-foreground': '#0D1016',
        '--background': '#131720',
        '--background-elevated': '#1F242E',
        '--background-panel': '#0D1016',
        '--foreground': '#BFBDB6',
        '--muted': '#1F242E',
        '--muted-foreground': '#636E78',
        '--destructive': '#D95757',
        '--success': '#AAD94C',
        '--error': '#D95757',
        '--warning': '#FF8F40',
    },
    tokens: {
        keyword: '#FF8F40',
        string: '#AAD94C',
        propertyName: '#59C2FF',
        variableName: '#BFBDB6',
        comment: '#636E78',
        annotation: '#E6B450',
    },
});

const synthwave84 = defineTheme({
    id: 'synthwave-84',
    name: "SynthWave '84",
    type: 'dark',
    vars: {
        '--primary': '#FF7EDB',
        '--primary-foreground': '#150F29',
        '--background': '#1C1537',
        '--background-elevated': '#271F47',
        '--background-panel': '#150F29',
        '--foreground': '#F2D9F2',
        '--muted': '#271F47',
        '--muted-foreground': '#848BBD',
        '--destructive': '#FE4450',
        '--success': '#72F1B8',
        '--error': '#FE4450',
        '--warning': '#FEDE5D',
    },
    tokens: {
        keyword: '#FEDE5D',
        string: '#FF8B39',
        propertyName: '#36F9F6',
        variableName: '#FF7EDB',
        comment: '#848BBD',
        annotation: '#F97E72',
    },
});

const everforestDark = defineTheme({
    id: 'everforest-dark',
    name: 'Everforest Dark',
    type: 'dark',
    vars: {
        '--primary': '#A7C080',
        '--primary-foreground': '#212724',
        '--background': '#2A322E',
        '--background-elevated': '#343C38',
        '--background-panel': '#212724',
        '--foreground': '#D3C6AA',
        '--muted': '#343C38',
        '--muted-foreground': '#859289',
        '--destructive': '#E67E80',
        '--success': '#A7C080',
        '--error': '#E67E80',
        '--warning': '#DBBC7F',
    },
    tokens: {
        keyword: '#E67E80',
        string: '#A7C080',
        propertyName: '#7FBBB3',
        variableName: '#D3C6AA',
        comment: '#859289',
        annotation: '#DBBC7F',
    },
});

const ayuMirage = defineTheme({
    id: 'ayu-mirage',
    name: 'Ayu Mirage',
    type: 'dark',
    vars: {
        '--primary': '#FFCC66',
        '--primary-foreground': '#1F2430',
        '--background': '#212635',
        '--background-elevated': '#2D3243',
        '--background-panel': '#181B26',
        '--foreground': '#CBCCC6',
        '--muted': '#2D3243',
        '--muted-foreground': '#5C6773',
        '--destructive': '#F28779',
        '--success': '#BAE67E',
        '--error': '#F28779',
        '--warning': '#FFA759',
    },
    tokens: {
        keyword: '#FFA759',
        string: '#BAE67E',
        propertyName: '#5CCFE6',
        variableName: '#CBCCC6',
        comment: '#5C6773',
        annotation: '#FFD580',
    },
});

const catppuccinFrappe = defineTheme({
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappé',
    type: 'dark',
    vars: {
        '--primary': '#CA9EE6',
        '--primary-foreground': '#303446',
        '--background': '#303446',
        '--background-elevated': '#414559',
        '--background-panel': '#292C3C',
        '--foreground': '#C6D0F5',
        '--muted': '#414559',
        '--muted-foreground': '#737994',
        '--destructive': '#E78284',
        '--success': '#A6D189',
        '--error': '#E78284',
        '--warning': '#E5C890',
    },
    tokens: {
        keyword: '#CA9EE6',
        string: '#A6D189',
        propertyName: '#8CAAEE',
        variableName: '#C6D0F5',
        comment: '#737994',
        annotation: '#EF9F76',
    },
});

const catppuccinMacchiato = defineTheme({
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    type: 'dark',
    vars: {
        '--primary': '#C6A0F6',
        '--primary-foreground': '#24273A',
        '--background': '#24273A',
        '--background-elevated': '#363A4F',
        '--background-panel': '#1E2030',
        '--foreground': '#CAD3F5',
        '--muted': '#363A4F',
        '--muted-foreground': '#6E738D',
        '--destructive': '#ED8796',
        '--success': '#A6DA95',
        '--error': '#ED8796',
        '--warning': '#EED49F',
    },
    tokens: {
        keyword: '#C6A0F6',
        string: '#A6DA95',
        propertyName: '#8AADF4',
        variableName: '#CAD3F5',
        comment: '#6E738D',
        annotation: '#F5A97F',
    },
});

const tokyoNightStorm = defineTheme({
    id: 'tokyo-night-storm',
    name: 'Tokyo Night Storm',
    type: 'dark',
    vars: {
        '--primary': '#BB9AF7',
        '--primary-foreground': '#24283B',
        '--background': '#24283B',
        '--background-elevated': '#2C2F44',
        '--background-panel': '#1F2335',
        '--foreground': '#A9B1D6',
        '--muted': '#2C2F44',
        '--muted-foreground': '#565F89',
        '--destructive': '#F7768E',
        '--success': '#9ECE6A',
        '--error': '#F7768E',
        '--warning': '#E0AF68',
    },
    tokens: {
        keyword: '#BB9AF7',
        string: '#9ECE6A',
        propertyName: '#7AA2F7',
        variableName: '#C0CAF5',
        comment: '#565F89',
        annotation: '#FF9E64',
    },
});

const monokaiProClassic = defineTheme({
    id: 'monokai-pro-classic',
    name: 'Monokai Pro Classic',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#272822',
        '--background': '#282923',
        '--background-elevated': '#3E3D32',
        '--background-panel': '#1E1F1A',
        '--foreground': '#F8F8F2',
        '--muted': '#3E3D32',
        '--muted-foreground': '#75715E',
        '--destructive': '#F92672',
        '--success': '#A6E22E',
        '--error': '#F92672',
        '--warning': '#E6DB74',
    },
    tokens: {
        keyword: '#F92672',
        string: '#E6DB74',
        propertyName: '#66D9EF',
        variableName: '#F8F8F2',
        comment: '#75715E',
        annotation: '#FD971F',
    },
});

const monokaiProMachine = defineTheme({
    id: 'monokai-pro-machine',
    name: 'Monokai Pro Machine',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#273035',
        '--background': '#273035',
        '--background-elevated': '#3A4449',
        '--background-panel': '#1E2629',
        '--foreground': '#F2FFFC',
        '--muted': '#3A4449',
        '--muted-foreground': '#6B7678',
        '--destructive': '#FF6188',
        '--success': '#A9DC76',
        '--error': '#FF6188',
        '--warning': '#FFD866',
    },
    tokens: {
        keyword: '#FF6188',
        string: '#FFD866',
        propertyName: '#78DCE8',
        variableName: '#F2FFFC',
        comment: '#6B7678',
        annotation: '#FC9867',
    },
});

const monokaiProOctagon = defineTheme({
    id: 'monokai-pro-octagon',
    name: 'Monokai Pro Octagon',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#282A39',
        '--background': '#282A39',
        '--background-elevated': '#3A3D4E',
        '--background-panel': '#1D1E2A',
        '--foreground': '#EAFFF4',
        '--muted': '#3A3D4E',
        '--muted-foreground': '#696D77',
        '--destructive': '#FF6188',
        '--success': '#A9DC76',
        '--error': '#FF6188',
        '--warning': '#FFD866',
    },
    tokens: {
        keyword: '#FF6188',
        string: '#FFD866',
        propertyName: '#78DCE8',
        variableName: '#EAFFF4',
        comment: '#696D77',
        annotation: '#FC9867',
    },
});

const monokaiProRistretto = defineTheme({
    id: 'monokai-pro-ristretto',
    name: 'Monokai Pro Ristretto',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#2C2525',
        '--background': '#2C2525',
        '--background-elevated': '#403838',
        '--background-panel': '#211C1C',
        '--foreground': '#FFF1F3',
        '--muted': '#403838',
        '--muted-foreground': '#72696A',
        '--destructive': '#FF6188',
        '--success': '#A9DC76',
        '--error': '#FF6188',
        '--warning': '#FFD866',
    },
    tokens: {
        keyword: '#FF6188',
        string: '#FFD866',
        propertyName: '#78DCE8',
        variableName: '#FFF1F3',
        comment: '#72696A',
        annotation: '#FC9867',
    },
});

const monokaiProSpectrum = defineTheme({
    id: 'monokai-pro-spectrum',
    name: 'Monokai Pro Spectrum',
    type: 'dark',
    vars: {
        '--primary': '#A9DC76',
        '--primary-foreground': '#212121',
        '--background': '#212121',
        '--background-elevated': '#333333',
        '--background-panel': '#1A1A1A',
        '--foreground': '#F7F1FF',
        '--muted': '#333333',
        '--muted-foreground': '#69676C',
        '--destructive': '#FC618D',
        '--success': '#7BD88F',
        '--error': '#FC618D',
        '--warning': '#FCE566',
    },
    tokens: {
        keyword: '#FC618D',
        string: '#FCE566',
        propertyName: '#7BD88F',
        variableName: '#F7F1FF',
        comment: '#69676C',
        annotation: '#FC9867',
    },
});

const rosePine = defineTheme({
    id: 'rose-pine',
    name: 'Rosé Pine',
    type: 'dark',
    vars: {
        '--primary': '#C4A7E7',
        '--primary-foreground': '#191724',
        '--background': '#1F1D2E',
        '--background-elevated': '#26233A',
        '--background-panel': '#191724',
        '--foreground': '#E0DEF4',
        '--muted': '#26233A',
        '--muted-foreground': '#6E6A86',
        '--destructive': '#EB6F92',
        '--success': '#9CCFD8',
        '--error': '#EB6F92',
        '--warning': '#F6C177',
    },
    tokens: {
        keyword: '#C4A7E7',
        string: '#9CCFD8',
        propertyName: '#EBBCBA',
        variableName: '#E0DEF4',
        comment: '#6E6A86',
        annotation: '#F6C177',
    },
});

const rosePineMoon = defineTheme({
    id: 'rose-pine-moon',
    name: 'Rosé Pine Moon',
    type: 'dark',
    vars: {
        '--primary': '#C4A7E7',
        '--primary-foreground': '#232136',
        '--background': '#2A273A',
        '--background-elevated': '#393552',
        '--background-panel': '#232136',
        '--foreground': '#E0DEF4',
        '--muted': '#393552',
        '--muted-foreground': '#6E6A86',
        '--destructive': '#EB6F92',
        '--success': '#9CCFD8',
        '--error': '#EB6F92',
        '--warning': '#F6C177',
    },
    tokens: {
        keyword: '#C4A7E7',
        string: '#9CCFD8',
        propertyName: '#EA9A97',
        variableName: '#E0DEF4',
        comment: '#6E6A86',
        annotation: '#F6C177',
    },
});

const solarizedDark = defineTheme({
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    vars: {
        '--primary': '#268BD2',
        '--primary-foreground': '#FDF6E3',
        '--background': '#073642',
        '--background-elevated': '#0A4050',
        '--background-panel': '#002B36',
        '--foreground': '#839496',
        '--muted': '#073642',
        '--muted-foreground': '#586E75',
        '--destructive': '#DC322F',
        '--success': '#859900',
        '--error': '#DC322F',
        '--warning': '#B58900',
    },
    tokens: {
        keyword: '#859900',
        string: '#2AA198',
        propertyName: '#268BD2',
        variableName: '#839496',
        comment: '#586E75',
        annotation: '#CB4B16',
    },
});

const blulocoDark = defineTheme({
    id: 'bluloco-dark',
    name: 'Bluloco Dark',
    type: 'dark',
    vars: {
        '--primary': '#5A92F2',
        '--primary-foreground': '#FFFFFF',
        '--background': '#1D1F2B',
        '--background-elevated': '#282B39',
        '--background-panel': '#14161F',
        '--foreground': '#C4C9D4',
        '--muted': '#282B39',
        '--muted-foreground': '#636874',
        '--destructive': '#E64C59',
        '--success': '#3FC56B',
        '--error': '#E64C59',
        '--warning': '#F5AE3D',
    },
    tokens: {
        keyword: '#FF6480',
        string: '#3FC56B',
        propertyName: '#10B1FE',
        variableName: '#9FB3C2',
        comment: '#636D83',
        annotation: '#F9C859',
    },
});

const fleetDark = defineTheme({
    id: 'fleet-dark',
    name: 'Fleet Dark',
    type: 'dark',
    vars: {
        '--primary': '#4B8DEC',
        '--primary-foreground': '#FFFFFF',
        '--background': '#18191B',
        '--background-elevated': '#252629',
        '--background-panel': '#090909',
        '--foreground': '#E0E1E4',
        '--muted': '#3E4147',
        '--muted-foreground': '#646B71',
        '--destructive': '#E1465E',
        '--success': '#169068',
        '--error': '#E1465E',
        '--warning': '#B07203',
    },
    tokens: {
        keyword: '#EBC88D',
        string: '#A8C5A0',
        propertyName: '#87C3FF',
        variableName: '#E0E1E4',
        comment: '#7E8388',
        annotation: '#CC7832',
    },
});

const fleetDarkPurple = defineTheme({
    id: 'fleet-dark-purple',
    name: 'Fleet Dark Purple',
    type: 'dark',
    vars: {
        '--primary': '#B174D9',
        '--primary-foreground': '#FFFFFF',
        '--background': '#1C1827',
        '--background-elevated': '#262136',
        '--background-panel': '#13101B',
        '--foreground': '#E0E1E4',
        '--muted': '#3E3852',
        '--muted-foreground': '#6A5F7A',
        '--destructive': '#E1465E',
        '--success': '#169068',
        '--error': '#E1465E',
        '--warning': '#B07203',
    },
    tokens: {
        keyword: '#C7A65D',
        string: '#62A362',
        propertyName: '#93A6F5',
        variableName: '#E0E1E4',
        comment: '#6A5F7A',
        annotation: '#E09B70',
    },
});

const nightOwl = defineTheme({
    id: 'night-owl',
    name: 'Night Owl',
    type: 'dark',
    vars: {
        '--primary': '#7E57C2',
        '--primary-foreground': '#FFFFFF',
        '--background': '#011628',
        '--background-elevated': '#122536',
        '--background-panel': '#010E19',
        '--foreground': '#D6DEEB',
        '--muted': '#122536',
        '--muted-foreground': '#637777',
        '--destructive': '#EF5350',
        '--success': '#22DA6E',
        '--error': '#EF5350',
        '--warning': '#FFCB8B',
    },
    tokens: {
        keyword: '#C792EA',
        string: '#ECC48D',
        propertyName: '#82AAFF',
        variableName: '#D6DEEB',
        comment: '#637777',
        annotation: '#ADDB67',
    },
});

const shadesOfPurple = defineTheme({
    id: 'shades-of-purple',
    name: 'Shades of Purple',
    type: 'dark',
    vars: {
        '--primary': '#FAD000',
        '--primary-foreground': '#2D2B55',
        '--background': '#2D2B55',
        '--background-elevated': '#322F5E',
        '--background-panel': '#1E1E3F',
        '--foreground': '#FFFFFF',
        '--muted': '#3E3C6E',
        '--muted-foreground': '#7E72C4',
        '--destructive': '#EC3A37',
        '--success': '#3AD900',
        '--error': '#EC3A37',
        '--warning': '#FF9D00',
    },
    tokens: {
        keyword: '#FF9D00',
        string: '#A5FF90',
        propertyName: '#FAD000',
        variableName: '#FFFFFF',
        comment: '#A599E9',
        annotation: '#FF628C',
    },
});

const vitesseDark = defineTheme({
    id: 'vitesse-dark',
    name: 'Vitesse Dark',
    type: 'dark',
    vars: {
        '--primary': '#53C67F',
        '--primary-foreground': '#121417',
        '--background': '#16181D',
        '--background-elevated': '#22252B',
        '--background-panel': '#0D0F11',
        '--foreground': '#C7CAD1',
        '--muted': '#22252B',
        '--muted-foreground': '#656972',
        '--destructive': '#D65C66',
        '--success': '#53C67F',
        '--error': '#D65C66',
        '--warning': '#E5A05B',
    },
    tokens: {
        keyword: '#CB7676',
        string: '#C98A7D',
        propertyName: '#4D9375',
        variableName: '#BD976A',
        comment: '#758575',
        annotation: '#6394BF',
    },
});

const highContrastDark = defineTheme({
    id: 'high-contrast-dark',
    name: 'High Contrast Dark',
    type: 'dark',
    vars: {
        '--primary': '#D4B3FF',
        '--primary-foreground': '#000000',
        '--background': '#000000',
        '--background-elevated': '#333333',
        '--background-panel': '#000000',
        '--foreground': '#FFFFFF',
        '--muted': '#333333',
        '--muted-foreground': '#999999',
        '--destructive': '#FF94B2',
        '--success': '#42FFA1',
        '--error': '#FF94B2',
        '--warning': '#FFE577',
    },
    tokens: {
        keyword: '#D4B3FF',
        string: '#42FFA1',
        propertyName: '#87C3FF',
        variableName: '#FFFFFF',
        comment: '#7CA668',
        annotation: '#FF94B2',
    },
});

// ── Light Themes ─────────────────────────────────────────────

const catppuccinLatte = defineTheme({
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    type: 'light',
    vars: {
        '--primary': '#8839EF',
        '--primary-foreground': '#FFFFFF',
        '--background': '#DCE0E8',
        '--background-elevated': '#E6E9EF',
        '--background-panel': '#EFF1F5',
        '--foreground': '#4C4F69',
        '--muted': '#CCD0DA',
        '--muted-foreground': '#9CA0B0',
        '--destructive': '#D20F39',
        '--success': '#40A02B',
        '--error': '#D20F39',
        '--warning': '#DF8E1D',
    },
    tokens: {
        keyword: '#8839EF',
        string: '#40A02B',
        propertyName: '#1E66F5',
        variableName: '#4C4F69',
        comment: '#9CA0B0',
        annotation: '#FE640B',
    },
});

const nordLight = defineTheme({
    id: 'nord-light',
    name: 'Nord Light',
    type: 'light',
    vars: {
        '--primary': '#5E81AC',
        '--primary-foreground': '#ECEFF4',
        '--background': '#E5E9F0',
        '--background-elevated': '#ECEFF4',
        '--background-panel': '#ECEFF4',
        '--foreground': '#2E3440',
        '--muted': '#D8DEE9',
        '--muted-foreground': '#4C566A',
        '--destructive': '#BF616A',
        '--success': '#A3BE8C',
        '--error': '#BF616A',
        '--warning': '#EBCB8B',
    },
    tokens: {
        keyword: '#81A1C1',
        string: '#A3BE8C',
        propertyName: '#88C0D0',
        variableName: '#2E3440',
        comment: '#4C566A',
        annotation: '#D08770',
    },
});

const blulocoLight = defineTheme({
    id: 'bluloco-light',
    name: 'Bluloco Light',
    type: 'light',
    vars: {
        '--primary': '#1860DC',
        '--primary-foreground': '#FFFFFF',
        '--background': '#EDEFF2',
        '--background-elevated': '#F3F4F6',
        '--background-panel': '#FAFAFA',
        '--foreground': '#3F445A',
        '--muted': '#E4E6EA',
        '--muted-foreground': '#8B8F9C',
        '--destructive': '#D02533',
        '--success': '#2E9E50',
        '--error': '#D02533',
        '--warning': '#DF631C',
    },
    tokens: {
        keyword: '#D52753',
        string: '#23974A',
        propertyName: '#275FE4',
        variableName: '#3F445A',
        comment: '#A0A1A7',
        annotation: '#DF631C',
    },
});

const fleetLight = defineTheme({
    id: 'fleet-light',
    name: 'Fleet Light',
    type: 'light',
    vars: {
        '--primary': '#1D61BA',
        '--primary-foreground': '#FFFFFF',
        '--background': '#EEEFF0',
        '--background-elevated': '#F8F8F9',
        '--background-panel': '#FFFFFF',
        '--foreground': '#090909',
        '--muted': '#E4E5E6',
        '--muted-foreground': '#6E747B',
        '--destructive': '#E1465E',
        '--success': '#169068',
        '--error': '#E1465E',
        '--warning': '#B07203',
    },
    tokens: {
        keyword: '#5511BF',
        string: '#086E14',
        propertyName: '#1749BD',
        variableName: '#090909',
        comment: '#898E94',
        annotation: '#A31D8D',
    },
});

const lightOwl = defineTheme({
    id: 'light-owl',
    name: 'Light Owl',
    type: 'light',
    vars: {
        '--primary': '#9600D1',
        '--primary-foreground': '#FFFFFF',
        '--background': '#EDF0F3',
        '--background-elevated': '#F3F5F7',
        '--background-panel': '#FAFAFA',
        '--foreground': '#403F53',
        '--muted': '#E4E8EC',
        '--muted-foreground': '#818798',
        '--destructive': '#C63939',
        '--success': '#1B984F',
        '--error': '#C63939',
        '--warning': '#C96765',
    },
    tokens: {
        keyword: '#994CC3',
        string: '#C96765',
        propertyName: '#4876D6',
        variableName: '#403F53',
        comment: '#989FB1',
        annotation: '#AA0982',
    },
});

const vitesseLight = defineTheme({
    id: 'vitesse-light',
    name: 'Vitesse Light',
    type: 'light',
    vars: {
        '--primary': '#3D8F5C',
        '--primary-foreground': '#FFFFFF',
        '--background': '#F5F3F0',
        '--background-elevated': '#F9F8F6',
        '--background-panel': '#FFFFFF',
        '--foreground': '#3D3D3D',
        '--muted': '#EFECEB',
        '--muted-foreground': '#8C8C8C',
        '--destructive': '#B83D5C',
        '--success': '#3D8F5C',
        '--error': '#B83D5C',
        '--warning': '#AB5E30',
    },
    tokens: {
        keyword: '#AB5959',
        string: '#B56959',
        propertyName: '#2E8F82',
        variableName: '#999999',
        comment: '#A0ADA0',
        annotation: '#296AA3',
    },
});

const highContrastLight = defineTheme({
    id: 'high-contrast-light',
    name: 'High Contrast Light',
    type: 'light',
    vars: {
        '--primary': '#7028C8',
        '--primary-foreground': '#FFFFFF',
        '--background': '#E9ECF1',
        '--background-elevated': '#F5F5F5',
        '--background-panel': '#FFFFFF',
        '--foreground': '#000000',
        '--muted': '#E0E3E8',
        '--muted-foreground': '#555555',
        '--destructive': '#B3004D',
        '--success': '#00854D',
        '--error': '#B3004D',
        '--warning': '#AD5701',
    },
    tokens: {
        keyword: '#7028C8',
        string: '#00854D',
        propertyName: '#1749BD',
        variableName: '#000000',
        comment: '#717171',
        annotation: '#AD5701',
    },
});

const githubLight = defineTheme({
    id: 'github-light',
    name: 'GitHub Light',
    type: 'light',
    vars: {
        '--primary': '#8250DF',
        '--primary-foreground': '#FFFFFF',
        '--background': '#F0F3F6',
        '--background-elevated': '#F6F8FA',
        '--background-panel': '#FFFFFF',
        '--foreground': '#1F2328',
        '--muted': '#F6F8FA',
        '--muted-foreground': '#656D76',
        '--destructive': '#CF222E',
        '--success': '#1A7F37',
        '--error': '#CF222E',
        '--warning': '#9A6700',
    },
    tokens: {
        keyword: '#CF222E',
        string: '#0A3069',
        propertyName: '#0550AE',
        variableName: '#24292F',
        comment: '#6E7781',
        annotation: '#953800',
    },
});

const ayuLight = defineTheme({
    id: 'ayu-light',
    name: 'Ayu Light',
    type: 'light',
    vars: {
        '--primary': '#F2AE49',
        '--primary-foreground': '#5C6166',
        '--background': '#F0EDE5',
        '--background-elevated': '#F5F3EE',
        '--background-panel': '#FCFCFC',
        '--foreground': '#5C6166',
        '--muted': '#F0F0EE',
        '--muted-foreground': '#8A9199',
        '--destructive': '#F07171',
        '--success': '#86B300',
        '--error': '#F07171',
        '--warning': '#FA8D3E',
    },
    tokens: {
        keyword: '#FA8D3E',
        string: '#86B300',
        propertyName: '#399EE6',
        variableName: '#5C6166',
        comment: '#ABB0B6',
        annotation: '#F2AE49',
    },
});

const everforestLight = defineTheme({
    id: 'everforest-light',
    name: 'Everforest Light',
    type: 'light',
    vars: {
        '--primary': '#8DA101',
        '--primary-foreground': '#FFFFFF',
        '--background': '#EBE6DB',
        '--background-elevated': '#EFEAE1',
        '--background-panel': '#F3EFE7',
        '--foreground': '#5C6A72',
        '--muted': '#E8E3D8',
        '--muted-foreground': '#939F91',
        '--destructive': '#F85552',
        '--success': '#8DA101',
        '--error': '#F85552',
        '--warning': '#DFA000',
    },
    tokens: {
        keyword: '#F85552',
        string: '#8DA101',
        propertyName: '#3A94C5',
        variableName: '#5C6A72',
        comment: '#939F91',
        annotation: '#DFA000',
    },
});

const tokyoNightDay = defineTheme({
    id: 'tokyo-night-day',
    name: 'Tokyo Night Day',
    type: 'light',
    vars: {
        '--primary': '#9854F1',
        '--primary-foreground': '#FFFFFF',
        '--background': '#DDE4F0',
        '--background-elevated': '#E8F0FA',
        '--background-panel': '#F5FAFF',
        '--foreground': '#343B59',
        '--muted': '#D5DEF0',
        '--muted-foreground': '#848CB5',
        '--destructive': '#C64343',
        '--success': '#587539',
        '--error': '#C64343',
        '--warning': '#8C6C3E',
    },
    tokens: {
        keyword: '#9854F1',
        string: '#587539',
        propertyName: '#2E7DE9',
        variableName: '#3760BF',
        comment: '#848CB5',
        annotation: '#B15C00',
    },
});

const postchiLight = defineTheme({
    id: 'postchi-light',
    name: 'Postchi Light',
    type: 'light',
    vars: {
        '--primary': '#2470B3',
        '--primary-foreground': '#FFFFFF',
        '--background': '#ECECEC',
        '--background-elevated': '#F7F7F7',
        '--background-panel': '#FFFFFF',
        '--foreground': '#1A1A1A',
        '--muted': '#EBEBEB',
        '--muted-foreground': '#757575',
        '--destructive': '#C7222A',
        '--success': '#2E7D32',
        '--error': '#DF0000',
        '--warning': '#ED6C02',
    },
    tokens: {
        keyword: '#D73A49',
        string: '#40A02B',
        propertyName: '#1E66F5',
        variableName: '#1A1A1A',
        comment: '#8C8C8C',
        annotation: '#E36209',
    },
});

const solarizedLight = defineTheme({
    id: 'solarized-light',
    name: 'Solarized Light',
    type: 'light',
    vars: {
        '--primary': '#268BD2',
        '--primary-foreground': '#FDF6E3',
        '--background': '#EEE8D5',
        '--background-elevated': '#FDF6E3',
        '--background-panel': '#FDF6E3',
        '--foreground': '#657B83',
        '--muted': '#EEE8D5',
        '--muted-foreground': '#93A1A1',
        '--destructive': '#DC322F',
        '--success': '#859900',
        '--error': '#DC322F',
        '--warning': '#B58900',
    },
    tokens: {
        keyword: '#859900',
        string: '#2AA198',
        propertyName: '#268BD2',
        variableName: '#657B83',
        comment: '#93A1A1',
        annotation: '#CB4B16',
    },
});

const rosePineDawn = defineTheme({
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    type: 'light',
    vars: {
        '--primary': '#907AA9',
        '--primary-foreground': '#FFFAF3',
        '--background': '#F2E9DE',
        '--background-elevated': '#FFFAF3',
        '--background-panel': '#FFFAF3',
        '--foreground': '#575279',
        '--muted': '#F2E9DE',
        '--muted-foreground': '#9893A5',
        '--destructive': '#B4637A',
        '--success': '#56949F',
        '--error': '#B4637A',
        '--warning': '#EA9D34',
    },
    tokens: {
        keyword: '#907AA9',
        string: '#56949F',
        propertyName: '#D7827E',
        variableName: '#575279',
        comment: '#9893A5',
        annotation: '#EA9D34',
    },
});

export const themes: PostchiTheme[] = [
    // Dark
    postchiDark,
    dracula,
    cobalt,
    catppuccinMocha,
    catppuccinMacchiato,
    catppuccinFrappe,
    tokyoNight,
    tokyoNightStorm,
    nord,
    githubDark,
    monokaiPro,
    monokaiProClassic,
    monokaiProMachine,
    monokaiProOctagon,
    monokaiProRistretto,
    monokaiProSpectrum,
    gruvbox,
    oneDarkPro,
    ayuDark,
    ayuMirage,
    synthwave84,
    everforestDark,
    rosePine,
    rosePineMoon,
    solarizedDark,
    blulocoDark,
    fleetDark,
    fleetDarkPurple,
    nightOwl,
    shadesOfPurple,
    vitesseDark,
    highContrastDark,
    // Light
    postchiLight,
    catppuccinLatte,
    githubLight,
    nordLight,
    ayuLight,
    everforestLight,
    tokyoNightDay,
    blulocoLight,
    fleetLight,
    lightOwl,
    vitesseLight,
    highContrastLight,
    solarizedLight,
    rosePineDawn,
];
