import { PostchiTheme } from "./theme";
import { amy, ayuLight, barf, bespin, birdsOfParadise, boysAndGirls, clouds, cobalt, coolGlow, dracula, espresso, noctisLilac, rosePineDawn, smoothy, solarizedLight, tomorrow } from 'thememirror';

export const themes: PostchiTheme[] = [
  {
    id: 'amy',
    name: 'Amy',
    vars: {
      '--primary': '#7070FF',
      '--background': '#140014',
      '--background-elevated': '#2a002a',
      '--muted': '#350035',
      '--background-panel': '#200020',
      '--foreground': '#D0D0FF',
      '--muted-foreground': '#C080C0',
      '--destructive': '#FF5060',
    },
    codemirrorTheme: amy,
  },
  {
    id: 'ayu-light',
    name: 'Ayu Light',
    vars: {
      '--primary': '#ffaa33',
      '--background': '#ebebeb',
      '--background-elevated': '#f3f3f3',
      '--muted': '#dcdcdc',
      '--background-panel': '#fcfcfc',
      '--foreground': '#5c6166',
      '--muted-foreground': '#8a9199',
      '--destructive': '#e65050',
    },
    codemirrorTheme: ayuLight,
  },
  {
    id: 'barf',
    name: 'Barf',
    vars: {
      '--primary': '#C4C4C4',
      '--background': '#0d1015',
      '--background-elevated': '#111519',
      '--muted': '#1e2530',
      '--background-panel': '#15191e',
      '--foreground': '#EEF2F7',
      '--muted-foreground': '#aaaaaa',
      '--destructive': '#ff4444',
    },
    codemirrorTheme: barf,
  },
  {
    id: 'bespin',
    name: 'Bespin',
    vars: {
      '--primary': '#cf7d34',
      '--background': '#1c1510',
      '--background-elevated': '#221a14',
      '--muted': '#2e2218',
      '--background-panel': '#2e241d',
      '--foreground': '#BAAE9E',
      '--muted-foreground': '#BAAE9E90',
      '--destructive': '#f07070',
    },
    codemirrorTheme: bespin,
  },
  {
    id: 'birds-of-paradise',
    name: 'Birds of Paradise',
    vars: {
      '--primary': '#EF5D32',
      '--background': '#2a1a1b',
      '--background-elevated': '#301e1f',
      '--muted': '#3f2a2b',
      '--background-panel': '#3b2627',
      '--foreground': '#E6E1C4',
      '--muted-foreground': '#E6E1C490',
      '--destructive': '#ef5350',
    },
    codemirrorTheme: birdsOfParadise,
  },
  {
    id: 'boys-and-girls',
    name: 'Boys and Girls',
    vars: {
      '--primary': '#E60065',
      '--background': '#000000',
      '--background-elevated': '#050a10',
      '--muted': '#0a1020',
      '--background-panel': '#000205',
      '--foreground': '#FFFFFF',
      '--muted-foreground': '#ffffff90',
      '--destructive': '#ff4455',
    },
    codemirrorTheme: boysAndGirls,
  },
  {
    id: 'clouds',
    name: 'Clouds',
    vars: {
      '--primary': '#46A609',
      '--background': '#e8e8e8',
      '--background-elevated': '#f0f0f0',
      '--muted': '#d8d8d8',
      '--background-panel': '#ffffff',
      '--foreground': '#000000',
      '--muted-foreground': '#00000070',
      '--destructive': '#C52727',
    },
    codemirrorTheme: clouds,
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    vars: {
      '--primary': '#FF9D00',
      '--background': '#001830',
      '--background-elevated': '#001e3d',
      '--muted': '#003060',
      '--background-panel': '#00254b',
      '--foreground': '#FFFFFF',
      '--muted-foreground': '#FFFFFF70',
      '--destructive': '#FF628C',
    },
    codemirrorTheme: cobalt,
  },
  {
    id: 'cool-glow',
    name: 'Cool Glow',
    vars: {
      '--primary': '#2BF1DC',
      '--background': '#020310',
      '--background-elevated': '#070620',
      '--muted': '#0d0b30',
      '--background-panel': '#060521',
      '--foreground': '#E0E0E0',
      '--muted-foreground': '#E0E0E090',
      '--destructive': '#ff4455',
    },
    codemirrorTheme: coolGlow,
  },
  {
    id: 'dracula',
    name: 'Dracula',
    vars: {
      '--primary': '#bd93f9',
      '--background': '#1e1f2b',
      '--background-elevated': '#21222c',
      '--muted': '#383a4a',
      '--background-panel': '#2d2f3f',
      '--foreground': '#f8f8f2',
      '--muted-foreground': 'rgb(144, 145, 148)',
      '--destructive': '#ff5555',
    },
    codemirrorTheme: dracula,
  },
  {
    id: 'espresso',
    name: 'Espresso',
    vars: {
      '--primary': '#2F6F9F',
      '--background': '#e8e8e8',
      '--background-elevated': '#f0f0f0',
      '--muted': '#d8d8d8',
      '--background-panel': '#FFFFFF',
      '--foreground': '#000000',
      '--muted-foreground': '#00000070',
      '--destructive': '#CF4F5F',
    },
    codemirrorTheme: espresso,
  },
  {
    id: 'noctis-lilac',
    name: 'Noctis Lilac',
    vars: {
      '--primary': '#5c49e9',
      '--background': '#dddbe8',
      '--background-elevated': '#e8e6f0',
      '--muted': '#d0cde0',
      '--background-panel': '#f2f1f8',
      '--foreground': '#0c006b',
      '--muted-foreground': '#0c006b70',
      '--destructive': '#ff5792',
    },
    codemirrorTheme: noctisLilac,
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    vars: {
      '--primary': '#d7827e',
      '--background': '#ede8e2',
      '--background-elevated': '#f3ede7',
      '--muted': '#e4ddd6',
      '--background-panel': '#faf4ed',
      '--foreground': '#575279',
      '--muted-foreground': '#57527970',
      '--destructive': '#b4637a',
    },
    codemirrorTheme: rosePineDawn,
  },
  {
    id: 'smoothy',
    name: 'Smoothy',
    vars: {
      '--primary': '#2EB43B',
      '--background': '#ebebeb',
      '--background-elevated': '#f5f5f5',
      '--muted': '#e0e0e0',
      '--background-panel': '#FFFFFF',
      '--foreground': '#000000',
      '--muted-foreground': '#00000070',
      '--destructive': '#E66C29',
    },
    codemirrorTheme: smoothy,
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    vars: {
      '--primary': '#268BD2',
      '--background': '#EEE8D5',
      '--background-elevated': '#f5efdc',
      '--muted': '#e4ddc8',
      '--background-panel': '#fef7e5',
      '--foreground': '#586E75',
      '--muted-foreground': '#586E7580',
      '--destructive': '#D30102',
    },
    codemirrorTheme: solarizedLight,
  },
  {
    id: 'tomorrow',
    name: 'Tomorrow',
    vars: {
      '--primary': '#4271AE',
      '--background': '#ebebeb',
      '--background-elevated': '#f5f5f5',
      '--muted': '#e0e0e0',
      '--background-panel': '#FFFFFF',
      '--foreground': '#4D4D4C',
      '--muted-foreground': '#4D4D4C80',
      '--destructive': '#C82829',
    },
    codemirrorTheme: tomorrow,
  },
];