// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bQVQPOOOOQO'#C`'#C`ObQQO'#C_OjQPO'#C_OOQO'#Ce'#CeQVQPOOOoQPO'#CbOOQO'#Cg'#CgQtQPOOOyQPO'#CaOOQO,58y,58yO!RQPO,58yO!WQQO,58yOOQO-E6c-E6cOOQO'#Cd'#CdO!`QPO,58|OOQO-E6e-E6eO!eQQO'#CfO!jQPO,58{OOQO1G.e1G.eO!rQPO1G.eO!wQPO1G.hOOQO,59Q,59QOOQO-E6d-E6dOOQO7+$P7+$PO#VQPO7+$S",
  stateData: "#h~OPOS~OVUO^PO_QO~O`XOaYO~O_[O~O^^O~OVUO~O_aOaTX~OacO~O`XOacO~OaeO~O`fO~O_aOaTa~OahO~O^PO_QOVUi[Ui~O^PO_QOVUq[Uq~O`P~",
  goto: "!`[PPP]cioPtw!R!XXSOTeiXROTeiQZQRd[VVOTWR_UQTOS]TiRieQbXRgbSWOTR`W",
  nodeNames: "⚠ Comment Environments Entry Key Value Environment Pound EnvironmentName",
  maxTerm: 17,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "%n~RbOY!ZYZ!rZs!Zst!wt!P!Z!P!Q#[!Q![$^![!_!Z!_!`%Z!`!c!Z!c!}$^!}#R!Z#R#S$^#S#T!Z#T#o$^#o;'S!Z;'S;=`!l<%lO!ZQ!`S`QOY!ZZ;'S!Z;'S;=`!l<%lO!ZQ!oP;=`<%l!Z~!wOa~R#OSVP`QOY!ZZ;'S!Z;'S;=`!l<%lO!Z~#aU`QOY!ZZ!P!Z!P!Q#s!Q;'S!Z;'S;=`!l<%lO!Z~#zS`QP~OY#sZ;'S#s;'S;=`$W<%lO#s~$ZP;=`<%l#sR$e[^P`QOY!ZZ!Q!Z!Q![$^![!c!Z!c!}$^!}#R!Z#R#S$^#S#T!Z#T#o$^#o;'S!Z;'S;=`!l<%lO!ZR%bS_P`QOY!ZZ;'S!Z;'S;=`!l<%lO!Z",
  tokenizers: [0, 1],
  topRules: {"Environments":[0,2]},
  tokenPrec: 113
})
