// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#xQVQPOOOOQO'#C`'#C`ObQQO'#C_OjQPO'#C_OOQO'#Ce'#CeQVQPOOOoQPO'#CbOOQO'#Cf'#CfQtQPOOOOQO'#Ca'#CaOOQO,58y,58yOyQPO,58yO!OQQO,58yOOQO-E6c-E6cOOQO'#Cd'#CdO!WQPO,58|OOQO-E6d-E6dOOQO1G.e1G.eO!]QPO1G.eO!bQPO1G.hOOQO7+$P7+$PO!pQPO7+$S",
  stateData: "#R~OPOS~OVUO]PO^QO~O_XO`YO~O^[O~O]^O~OVUO~O`aO~O_XO`aO~O`cO~O`dO~O]PO^QOVUiZUi~O]PO^QOVUqZUq~O_P~",
  goto: "!XZPPP[bhnPsv!QXSOTceXROTceQZQRb[VVOTWR_UQTOS]TeRecSWOTR`W",
  nodeNames: "⚠ Comment Environments Entry Key Value Environment Pound EnvironmentName",
  maxTerm: 16,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "&^~RYYZqstv!O!P!g!P!Q#U!Q![%h![!]!g!_!`&X!c!}%h#R#S%h#T#o%h~vO`~R}WVP_Qst!g!O!P!g!P!Q!g!Q![!g![!]!g!c!}!g#R#S!g#T#o!gQ!lW_Qst!g!O!P!g!P!Q!g!Q![!g![!]!g!c!}!g#R#S!g#T#o!g~#ZW_Qst!g!O!P!g!P!Q#s!Q![!g![!]!g!c!}!g#R#S!g#T#o!g~#za_QP~OY%PZs%Pst#st!O%P!O!P#s!P!Q#s!Q![#s![!]#s!]!c%P!c!}#s!}#R%P#R#S#s#S#T%P#T#o#s#o;'S%P;'S;=`%b<%lO%P~%USP~OY%PZ;'S%P;'S;=`%b<%lO%P~%eP;=`<%l%PR%oW]P_Qst!g!O!P!g!P!Q!g!Q![%h![!]!g!c!}%h#R#S%h#T#o%h~&^O^~",
  tokenizers: [0, 1],
  topRules: {"Environments":[0,2]},
  tokenPrec: 92
})
