// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bQVQPOOOOQO'#C`'#C`ObQQO'#C_OjQPO'#C_OOQO'#Ce'#CeQVQPOOOoQPO'#CbOOQO'#Cg'#CgQtQPOOOyQPO'#CaOOQO,58y,58yO!RQPO,58yO!WQQO,58yOOQO-E6c-E6cOOQO'#Cd'#CdO!`QPO,58|OOQO-E6e-E6eO!eQQO'#CfO!jQPO,58{OOQO1G.e1G.eO!rQPO1G.eO!wQPO1G.hOOQO,59Q,59QOOQO-E6d-E6dOOQO7+$P7+$PO#VQPO7+$S",
  stateData: "#h~OPOS~OVUO^PO_QO~O`XOaYO~O_[O~O^^O~OVUO~O_aOaTX~OacO~O`XOacO~OaeO~O`fO~O_aOaTa~OahO~O^PO_QOVUi[Ui~O^PO_QOVUq[Uq~O`P~",
  goto: "!`[PPP]cioPtw!R!XXSOTeiXROTeiQZQRd[VVOTWR_UQTOS]TiRieQbXRgbSWOTR`W",
  nodeNames: "⚠ Comment Environments Entry Key Value Environment Pound EnvironmentName",
  maxTerm: 17,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "'l~R]YZzst!Pvw!y}!O!y!O!P!y!P!Q#q!Q![&m![!]!y!_!`'g!a!b!y!c!}&m#R#S&m#T#o&m~!POa~R!WZVP`Qst!yvw!y}!O!y!O!P!y!P!Q!y!Q![!y![!]!y!a!b!y!c!}!y#R#S!y#T#o!yQ#OZ`Qst!yvw!y}!O!y!O!P!y!P!Q!y!Q![!y![!]!y!a!b!y!c!}!y#R#S!y#T#o!y~#vZ`Qst!yvw!y}!O!y!O!P!y!P!Q$i!Q![!y![!]!y!a!b!y!c!}!y#R#S!y#T#o!y~$pf`QP~OY&UZs&Ust$itv&Uvw$iw}&U}!O$i!O!P$i!P!Q$i!Q![$i![!]$i!]!a&U!a!b$i!b!c&U!c!}$i!}#R&U#R#S$i#S#T&U#T#o$i#o;'S&U;'S;=`&g<%lO&U~&ZSP~OY&UZ;'S&U;'S;=`&g<%lO&U~&jP;=`<%l&UR&tZ^P`Qst!yvw!y}!O!y!O!P!y!P!Q!y!Q![&m![!]!y!a!b!y!c!}&m#R#S&m#T#o&m~'lO_~",
  tokenizers: [0, 1],
  topRules: {"Environments":[0,2]},
  tokenPrec: 113
})
