// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Environments = 2,
  Entry = 3,
  Key = 4,
  Value = 5,
  Environment = 6,
  Pound = 7,
  EnvironmentName = 8
